### PR TITLE
Use specific commit of ULS

### PR DESCRIPTION
**Pull request by schana**
This will work around #42 for now.

I tried updating to the latest ULS, but there were other regressions that we may need to address (like the language search wasn't limiting itself to our provided values) before updating.

### CODE REVIEW

**Comment by Nikerabbit** [comment]
If you see regressions in jquery.uls code, please let us know.

**Comment by schana** [comment]
@Nikerabbit We're using it in a fairly hacky way, so I'm not sure if it's our use that's causing the regression. I am overwriting the internal searchAPI function (https://github.com/wikimedia-research/translation-recs-app/blob/master/api/static/gf-input.tag#L220), so if that changed it would explain the failure.

**Comment by Nikerabbit** [comment]
That should be okay and I don't remember us changing how the search API is used. We did change the code that shows the search results though. There is also option to pass the set of available languages, are you using that option?

**Comment by schana** [comment]
Yes, we're using that option. However it doesn't work due to CORS with the way the ajax request is being made (as far as I can tell).

**Pull request merged**
