### PR TITLE
Feedback while searching

### PR DESCRIPTION
**Pull request by sabyasachi**
https://phabricator.wikimedia.org/T134292

### CODE REVIEW

**Comment by sabyasachi** [comment]
Here is the first working copy.

Notes:

- I changed the wm-typeahead.js and corresponding CSS little bit to suit our need.

Todo:

- [ ] why can't we add one 'id' in the text input field
- [ ] pressing 'enter' does not trigger the search
- [ ] changing the source language should clear the existing seed

**Comment by schana** [comment]
> I changed the wm-typeahead.js and corresponding CSS little bit to suit our need.

Could you make it clear what you changed and why with comments?

> Organization of files inside the suggest-searches dir. Is that OK? Should they go as bower packages?

It would be nice if we could reference the originals (are they from [here](https://github.com/wikimedia/portals/tree/master/dev/wikipedia.org/assets)?) instead of maintaining local copies.

> Why can't we add one 'id' in the text input field

I'm not sure what you mean by this.

> pressing 'enter' does not trigger the search

I'm not sure how I feel about this. The API does a search based on that field, even if it is already a valid article. It then finds the most likely match, and uses it as the seed. There's room for improvement with how the API handles the field, but removing the option to perform that kind of search through the UI isn't good.
Options (as I see them) for moving forward:
1. Remove raw searching through the UI and rely on the search feedback
2. Leave the option to manually search. For this to be viable, I think we need to have a way to show the user how the search term is actually being used with regards to picking a seed

> autocomplete should be off in the text input

Is this an issue on mobile?

**Comment by sabyasachi** [comment]
>> I changed the wm-typeahead.js and corresponding CSS little bit to suit our need.

> Could you make it clear what you changed and why with comments?

Below are the changes with explanation:

- Customizable handler on select of a suggestion:
   
In the original wm-typeahead.js was if you select any suggestion from
the suggestions box it will load the article page. We wanted it just
to fill the search input plus fire `fetchArticles`. For this I made
the constructor of WMTypeAhead take one more callback which basically
should is a handler.

``` javascript
< var WMTypeAhead = function ( appendTo, searchInput ) {
---
> var WMTypeAhead = function ( appendTo, searchInput, callback ) {

``` 

- Ability to pass jQuery friendly selectors for `appendTo` and
   `searchInput`. This I did for two reasons: 
   
   a) consistency with jQuery
   
   b) If I was adding `id` to `searchInput` element in gf-input.tag,
   acessing `this.seedArticle.value` was failing with error `Cannot
   read property 'value' of undefined`. This is what I meant in my
   earlier comment when I said "Why can't we add one 'id' in the text
   input field". I would like to figure out the reason.

``` javascript
<         appendEl = document.getElementById( appendTo ),
<         searchEl = document.getElementById( searchInput ),
---
>         appendEl = $(appendTo)[0], 
>         searchEl = $(searchInput)[0], 

```

- Attaching the custom handler on click of of suggestion.
   
``` javascript
>             $('.suggestion-link').click(function(event){
>                 event.preventDefault();
>                 var val = $.data(this, 'data');
>                 callback(event, val);
>                 clearTypeAhead();
>             });
>
>                 // associate data
>                 $.data(listEl, 'data', orderedResults[i]);**

```

**Comment by sabyasachi** [comment]
>> Organization of files inside the suggest-searches dir. Is that OK? Should they go as bower packages?

> It would be nice if we could reference the originals (are they from here?) instead of maintaining local copies.

Since I had to change the files for the above reasons, I could not reference the originals.

>> Why can't we add one 'id' in the text input field

> I'm not sure what you mean by this.

Explained in previous comment. See second reason's point b.

> pressing 'enter' does not trigger the search

This was note-to-self. Fixed now. Basically, I wanted to have the ability to select a suggestion using the keyboard by pressing the enter/return key.

> autocomplete should be off in the text input

This was note-to-self. Fixed now. Basically I wanted to disable browser auto complete:

``` html
-                    <input type="text" class="form-control seed-input"
+                    <input type="text" autocomplete=off class="form-control seed-input"

```

**Comment by schana** [comment]
Everything looks good except two things:

1. Pressing 'enter' from the search box doesn't hide the suggested items, even though it loads the articles in the background
2. After selecting an item from the suggested items, changing the search string and pressing 'enter' results in the text being replaced with the previously selected item.

**Comment by sabyasachi** [comment]
@schana fixed both

**Pull request merged**
