### PR TITLE
Better placeholder image for articles with no image

### PR DESCRIPTION
**Pull request by sabyasachi**
https://phabricator.wikimedia.org/T134295

### CODE REVIEW

**Comment by schana** [comment]
I'm inclined to not have the custom placeholder css class. I'd be happy to change the background color to white globally. I'd also like to have more of a discussion regarding changing from `contain` to `cover` (#49).

**Comment by sabyasachi** [comment]
In that case, let's discuss and close #49 first. Where do we discuss this, design doc or Phab task?

**Comment by schana** [comment]
I think Phab would be okay, since it's already somewhat started on the ticket.

**Comment by schana** [comment]
Hey @sabyasachi, are we able to have the placeholder image work without the need for a custom css class?

**Comment by sabyasachi** [comment]
@schana I can do it if I get a properly scaled placeholder image. The current pencil in a hand image does not scale properly in "cover" background-size. I am pushing this change for now with a simple pattern, would be great if I get a nicer image. Let me know if it looks OK, I'll squash the commits then.

**Pull request merged**
